platform :ios, '7.0'

target 'Yoosee' do

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../rn/node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTActionSheet',
    # Add any other subspecs you want to use in your project
  ]

end